version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: doctorbook-db
    environment:
      POSTGRES_DB: doctorbook
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - doctorbook-network

  # เพิ่ม Redis ทีหลังเมื่อต้องการ caching
  # redis:
  #   image: redis:alpine
  #   container_name: doctorbook-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - doctorbook-network

volumes:
  postgres_data:

networks:
  doctorbook-network:
    driver: bridge