[phases.setup]
nixPkgs = ["...", "openjdk17"]

[phases.build]
cmds = [
  "./mvnw clean package -DskipTests",
  "ls -la target/"
]

[start]
cmd = "java -Dserver.port=$PORT -jar target/Doctoralia-0.0.1-SNAPSHOT.jar"