[phases.setup]
nixPkgs = ["...", "openjdk17"]

[phases.build]
cmds = [
  "./mvnw clean package -DskipTests",
  "ls -la target/"
]

[start]
cmd = "JDBC_DATABASE_URL=$(echo $DATABASE_URL | sed 's/^postgresql:/jdbc:postgresql:/') java -Dserver.port=$PORT -jar target/Doctoralia-0.0.1-SNAPSHOT.jar"