[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/Doctoralia-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/specialties"
healthcheckTimeout = 300
numReplicas = 1
restartPolicyMaxRetries = 10
