[build]
builder = "nixpacks"

[deploy]
startCommand = "java -Xmx512m -Xms256m -jar target/Doctoralia-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 180
restartPolicyMaxRetries = 10

# Environment variables
[[deploy.environmentVariables]]
name = "CORS_ORIGINS"
value = "https://frontenddoctora-production-0742.up.railway.app"

# CRITICAL: Ensure Spring Boot starts on Railway's PORT
[[deploy.environmentVariables]]
name = "SERVER_PORT"
value = "$PORT"