[build]
builder = "nixpacks"

[deploy]
startCommand = "JDBC_DATABASE_URL=$(echo $DATABASE_URL | sed 's/^postgresql:/jdbc:postgresql:/') java -jar target/Doctoralia-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/specialties"
healthcheckTimeout = 300
numReplicas = 1
restartPolicyMaxRetries = 10

# Environment variables
[[deploy.environmentVariables]]
name = "CORS_ORIGINS"
value = "https://frontenddoctora-production-0742.up.railway.app"
